# Generated by Django 3.1.7 on 2021-02-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='commands are named like this e.g order, make_refund. no spaces allowed or special characters allowed', max_length=15)),
                ('description', models.TextField(help_text='what does this command do')),
                ('example', models.TextField(help_text='example usage of this command')),
            ],
        ),
    ]
