# Generated by Django 3.1.7 on 2021-02-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='name',
            field=models.CharField(help_text='commands are named like this e.g order, make_refund. no spaces allowed or special characters allowed', max_length=15, unique=True),
        ),
    ]
