# Generated by Django 3.1.7 on 2021-02-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='user phone number e.g +23409050039030', max_length=15, null=True, unique=True),
        ),
    ]
