# Generated by Django 3.1.7 on 2021-02-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210228_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='successful',
            new_name='success',
        ),
    ]
