# Generated by Django 3.1.7 on 2021-03-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cartitem'),
        ),
    ]
