# Generated by Django 3.1.7 on 2021-03-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210302_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='contact',
            field=models.CharField(help_text='user phone number e.g +23409050039030', max_length=15, null=True),
        ),
    ]
