# Generated by Django 3.1.7 on 2021-03-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20210302_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.EmailField(default='oladele.alade@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
