# Generated by Django 3.1.7 on 2021-03-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fees',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
